In [3]:
import numpy as np

In [1]:
my_list=[1,2,3,4,5]

In [4]:
arr=np.array(my_list)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.shape

(5,)

In [9]:
# multiple array

my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[3,4,5,6,7]

arr=np.array([my_list1,my_list2,my_list3])

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [11]:
arr.shape

(3, 5)

In [12]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [15]:
array=np.array([1,2,3,4,5,6,7,8,9])

In [17]:
array[3]

np.int64(4)

In [13]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [18]:
arr[0:3,0:1]

array([[1],
       [2],
       [3]])

In [19]:
arr[1:,3:]

array([[5, 6],
       [6, 7]])

In [30]:
arr[1:,0:2]

array([[2, 3],
       [3, 4]])

In [54]:
arr=np.arange(0,10)

In [55]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.linspace(1,10,60)

array([ 1.        ,  1.15254237,  1.30508475,  1.45762712,  1.61016949,
        1.76271186,  1.91525424,  2.06779661,  2.22033898,  2.37288136,
        2.52542373,  2.6779661 ,  2.83050847,  2.98305085,  3.13559322,
        3.28813559,  3.44067797,  3.59322034,  3.74576271,  3.89830508,
        4.05084746,  4.20338983,  4.3559322 ,  4.50847458,  4.66101695,
        4.81355932,  4.96610169,  5.11864407,  5.27118644,  5.42372881,
        5.57627119,  5.72881356,  5.88135593,  6.03389831,  6.18644068,
        6.33898305,  6.49152542,  6.6440678 ,  6.79661017,  6.94915254,
        7.10169492,  7.25423729,  7.40677966,  7.55932203,  7.71186441,
        7.86440678,  8.01694915,  8.16949153,  8.3220339 ,  8.47457627,
        8.62711864,  8.77966102,  8.93220339,  9.08474576,  9.23728814,
        9.38983051,  9.54237288,  9.69491525,  9.84745763, 10.        ])

In [57]:
# copy() function and nroadcasting
arr[3:]=100

In [58]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [59]:
arr1=arr
arr1[3:]=500

In [60]:
print (arr1)

[  0   1   2 500 500 500 500 500 500 500]


In [61]:
arr1=arr.copy()

In [62]:
print(arr)
arr1[3:]=1000
print(arr1)

[  0   1   2 500 500 500 500 500 500 500]
[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


In [66]:
# some condition very useful in exploratory data analysis

val=2

arr[arr<2]

array([0, 1])

In [68]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [70]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
# random distribution
np.random.rand(3,4)


array([[0.54935757, 0.27588364, 0.09108566, 0.22408366],
       [0.23720981, 0.00565855, 0.28732745, 0.38674403],
       [0.63918316, 0.85546624, 0.09203019, 0.51047995]])

In [76]:
arr_ex=np.random.rand(4,4)

In [77]:
arr_ex

array([[0.79348662, 0.56394711, 0.08683965, 0.22967815],
       [0.7927203 , 0.60314069, 0.0214633 , 0.32432547],
       [0.34782692, 0.99375278, 0.4106477 , 0.51012384],
       [0.59022606, 0.51500372, 0.05456708, 0.03450165]])

In [79]:
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [83]:
np.random.randint(0,50,8).reshape(2,4)

array([[ 9, 31, 41, 35],
       [29, 24, 31, 36]], dtype=int32)